import { genreDescriptions } from '../../data/genre-descriptions';
import { tagFacet } from '../steam-tags';

/**
 * Valve's tag names are browsing labels; the sentence needs the spoken form. Initialisms are
 * expanded so the reading stays a sentence ("a real-time strategy game", not "an RTS game"),
 * and Valve's disambiguating parentheses — `Football (American)` — become how the sport is
 * actually said.
 */
const GENRE_PHRASES: Record<string, string> = {
  RPG: 'role-playing',
  'Action RPG': 'action role-playing',
  'Strategy RPG': 'strategy role-playing',
  'Party-Based RPG': 'party-based role-playing',
  'Tactical RPG': 'tactical role-playing',
  RTS: 'real-time strategy',
  'Action RTS': 'action real-time strategy',
  'Real Time Tactics': 'real-time tactics',
  'Twin Stick Shooter': 'twin-stick shooter',
  'Point & Click': 'point-and-click',
  'Hack and Slash': 'hack-and-slash',
  "Shoot 'Em Up": "shoot-'em-up",
  "Beat 'em up": "beat-'em-up",
  'Choose Your Own Adventure': 'choose-your-own-adventure',
  'Open World Survival Craft': 'open-world survival-craft',
  'Match 3': 'match-3',
  'Mini Golf': 'mini-golf',
  'Shop Keeper': 'shopkeeper',
  'Football (American)': 'American football',
  'Football (Soccer)': 'football',
};

/**
 * Four genres roll at once, and Steam's list is a mesh of umbrellas and specialisations.
 * A tag belongs to every family it is a member of, and one member of a family rolls at a
 * time: `Action RPG` is an RPG and an action game, so it blocks both; every sport is a sport,
 * so an idea is about one game, not cricket and snowboarding at once.
 */
const GENRE_FAMILIES: Record<string, readonly string[]> = {
  Action: ['action'],
  'Action-Adventure': ['adventure', 'action'],
  'Action Roguelike': ['roguelike', 'action'],
  'Action RPG': ['rpg', 'action'],
  'Action RTS': ['strategy', 'action'],
  RPG: ['rpg'],
  'Strategy RPG': ['rpg', 'strategy'],
  'Party-Based RPG': ['rpg'],
  'Tactical RPG': ['rpg', 'tactics'],
  CRPG: ['rpg'],
  JRPG: ['rpg'],
  MMORPG: ['rpg'],
  Roguelike: ['roguelike'],
  Roguelite: ['roguelike'],
  'Traditional Roguelike': ['roguelike'],
  'Roguelike Deckbuilder': ['roguelike', 'cards'],
  'Mystery Dungeon': ['roguelike', 'dungeon'],
  'Dungeon Crawler': ['dungeon'],
  Shooter: ['shooter'],
  FPS: ['shooter'],
  'Arena Shooter': ['shooter'],
  'Boomer Shooter': ['shooter'],
  'Hero Shooter': ['shooter'],
  'Looter Shooter': ['shooter'],
  'Extraction Shooter': ['shooter'],
  'On-Rails Shooter': ['shooter'],
  'Twin Stick Shooter': ['shooter'],
  "Shoot 'Em Up": ['shooter', 'bullets'],
  'Bullet Hell': ['bullets'],
  'Bullet Heaven': ['bullets'],
  Platformer: ['platformer'],
  'Precision Platformer': ['platformer'],
  'Puzzle Platformer': ['platformer', 'puzzle'],
  Metroidvania: ['platformer'],
  Fighting: ['fighting'],
  'Spectacle fighter': ['fighting'],
  "Beat 'em up": ['fighting', 'brawler'],
  'Hack and Slash': ['brawler'],
  Musou: ['brawler'],
  Strategy: ['strategy'],
  RTS: ['strategy'],
  'Turn-Based Strategy': ['strategy'],
  'Grand Strategy': ['strategy'],
  '4X': ['strategy'],
  'Real Time Tactics': ['tactics'],
  'Turn-Based Tactics': ['tactics'],
  Wargame: ['tactics'],
  Puzzle: ['puzzle'],
  'Match 3': ['puzzle'],
  'Falling Blocks': ['puzzle'],
  Sokoban: ['puzzle'],
  'Hidden Object': ['puzzle'],
  'Escape Room': ['puzzle'],
  'Card Game': ['cards', 'tabletop'],
  'Trading Card Game': ['cards', 'tabletop'],
  'Card Battler': ['cards'],
  Deckbuilding: ['cards'],
  Solitaire: ['cards'],
  Poker: ['cards'],
  'Board Game': ['tabletop'],
  Tabletop: ['tabletop'],
  Chess: ['tabletop'],
  Mahjong: ['tabletop'],
  Dice: ['tabletop'],
  Racing: ['racing'],
  'Combat Racing': ['racing'],
  Motocross: ['racing', 'sports'],
  Adventure: ['adventure'],
  Exploration: ['adventure'],
  Idler: ['incremental'],
  Incremental: ['incremental'],
  Clicker: ['incremental'],
  Simulation: ['sim'],
  'Automobile Sim': ['sim'],
  'Colony Sim': ['sim', 'builder'],
  'Dating Sim': ['sim'],
  'Farming Sim': ['sim'],
  'Hobby Sim': ['sim'],
  'Immersive Sim': ['sim'],
  'Job Simulator': ['sim'],
  'Life Sim': ['sim'],
  'Medical Sim': ['sim'],
  'Outbreak Sim': ['sim'],
  'Political Sim': ['sim'],
  'Space Sim': ['sim'],
  'City Builder': ['builder'],
  'God Game': ['builder'],
  'Visual Novel': ['narrative'],
  'Interactive Fiction': ['narrative'],
  'Choose Your Own Adventure': ['narrative'],
  'Walking Simulator': ['narrative'],
  'Word Game': ['words'],
  Spelling: ['words'],
  Typing: ['words'],
  Sports: ['sports'],
  Baseball: ['sports'],
  Basketball: ['sports'],
  Billiards: ['sports'],
  Bowling: ['sports'],
  Boxing: ['sports'],
  Cricket: ['sports'],
  Cycling: ['sports'],
  'Football (American)': ['sports'],
  'Football (Soccer)': ['sports'],
  Golf: ['sports', 'golf'],
  'Mini Golf': ['sports', 'golf'],
  Hockey: ['sports'],
  Rugby: ['sports'],
  Skateboarding: ['sports'],
  Skating: ['sports'],
  Skiing: ['sports', 'snow'],
  Snowboarding: ['sports', 'snow'],
  Tennis: ['sports'],
  Volleyball: ['sports'],
  Wrestling: ['sports', 'fighting'],
};

export const genreFacet = tagFacet({
  id: 'genre',
  label: 'Genre',
  hint: 'What kind of game it is',
  slot: 'prefix',
  icon: 'gamepad',
  enabledByDefault: true,
  hue: 255,
  count: { min: 1, max: 4, default: 2 },
  group: 'genre',
  phrases: GENRE_PHRASES,
  descriptions: genreDescriptions,
  families: GENRE_FAMILIES,
});
