import { genreDescriptions } from '../../data/genre-descriptions';
import { tagFacet } from '../steam-tags';

export const genreFacet = tagFacet({
  id: 'genre',
  label: 'Genre',
  hint: 'What kind of game it is',
  slot: 'prefix',
  icon: 'gamepad',
  enabledByDefault: true,
  hue: 255,
  count: { min: 1, max: 4, default: 2 },
  group: 'genre',
  phrases: {
    RPG: 'role-playing',
    'Action RPG': 'action role-playing',
    'Strategy RPG': 'strategy role-playing',
    'Party-Based RPG': 'party-based role-playing',
    'Tactical RPG': 'tactical role-playing',
    RTS: 'real-time strategy',
    'Action RTS': 'action real-time strategy',
    FPS: 'first-person shooter',
    'Point & Click': 'point-and-click',
    'Hack and Slash': 'hack-and-slash',
    "Shoot 'Em Up": "shoot-'em-up",
    "Beat 'em up": "beat-'em-up",
    'Choose Your Own Adventure': 'choose-your-own-adventure',
    'Open World Survival Craft': 'open-world survival-craft',
    'Match 3': 'match-3',
  },
  descriptions: genreDescriptions,
  // Near-synonyms: two members of one family in the same sentence describe the same game
  // twice ("role-playing action role-playing", "roguelike deckbuilder traditional roguelike").
  families: {
    RPG: 'rpg',
    'Action RPG': 'rpg',
    'Strategy RPG': 'rpg',
    'Party-Based RPG': 'rpg',
    'Tactical RPG': 'rpg',
    CRPG: 'rpg',
    JRPG: 'rpg',
    MMORPG: 'rpg',
    Roguelike: 'roguelike',
    Roguelite: 'roguelike',
    'Action Roguelike': 'roguelike',
    'Traditional Roguelike': 'roguelike',
    'Roguelike Deckbuilder': 'roguelike',
    Shooter: 'shooter',
    FPS: 'shooter',
    'Arena Shooter': 'shooter',
    'Boomer Shooter': 'shooter',
    'Hero Shooter': 'shooter',
    'Looter Shooter': 'shooter',
    'Extraction Shooter': 'shooter',
    'On-Rails Shooter': 'shooter',
    'Third-Person Shooter': 'shooter',
    'Top-Down Shooter': 'shooter',
    'Twin Stick Shooter': 'shooter',
    "Shoot 'Em Up": 'shooter',
    Platformer: 'platformer',
    '2D Platformer': 'platformer',
    '3D Platformer': 'platformer',
    'Precision Platformer': 'platformer',
    'Puzzle Platformer': 'platformer',
    Fighting: 'fighting',
    '2D Fighter': 'fighting',
    '3D Fighter': 'fighting',
    'Spectacle fighter': 'fighting',
    "Beat 'em up": 'fighting',
    Strategy: 'strategy',
    RTS: 'strategy',
    'Action RTS': 'strategy',
    'Turn-Based Strategy': 'strategy',
    'Grand Strategy': 'strategy',
    '4X': 'strategy',
    'Real Time Tactics': 'tactics',
    'Turn-Based Tactics': 'tactics',
    'Card Game': 'cards',
    'Trading Card Game': 'cards',
    'Card Battler': 'cards',
    Deckbuilding: 'cards',
    Racing: 'racing',
    'Combat Racing': 'racing',
    Adventure: 'adventure',
    'Action-Adventure': 'adventure',
    Idler: 'incremental',
    Incremental: 'incremental',
  },
});
